name: Python Application

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements file

    - name: Run tests with pytest
      run: |
        pytest test_app.py
        pytest --cov=app test_app.py # Run tests and generate coverage report

    - name: Check type errors with Mypy
      run: |
        mypy app.py  # Run Mypy on your application
